### ISSUE TITLE
Transition Distribution Images

### ISSUE THREAD

**Issue by Abc11c** [liuxhym/EDIS#1]
Hi @liuxhym, 

Thank you very much for releasing the code!

I was wondering how to generate the images on page 20 about the transition distributions.

Would it be possible to share a sample script for that?

Thanks!

**Comment by liuxhym** [comment]
Sorry for the late reply. Since the version of the code for generating this image is old, we spent some time adapting it to the new code. The code to generate the distribution has been added to the repository, under the toy/ folder. You can generate the image by running `python toy/state_dist.py`.
